---
services:
  ics-service:
    image: incora.azurecr.io/ics-service:stable
    container_name: ics-service-prod
    ports:
      - "9090:9090"  # Application port
      - "9091:9091"  # Management/Actuator port
    environment:
      # Database configuration
      - DB_URL=jdbc:oracle:thin:@oracle-db-prod:1521:ORCL
      - DB_PASSWORD=${TCMIS_DB_SECRET}
      # Spring configuration
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle-db-prod:1521:ORCL
      - SPRING_DATASOURCE_USERNAME=tcm_ops
      - SPRING_DATASOURCE_PASSWORD=${TCMIS_DB_SECRET}
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver
      # Azure AD configuration
      - SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_ENABLED=true
      - SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_CREDENTIAL_CLIENT_ID=a390d735-8347-4ef1-8a65-875d1410e88c
      - SPRING_CLOUD_AZURE_ACTIVE_DIRECTORY_APP_ID_URI=api://a390d735-8347-4ef1-8a65-875d1410e88c
      # Server configuration
      - SERVER_PORT=9090
      - SERVER_SERVLET_CONTEXT_PATH=/chemicals/api
      - MANAGEMENT_SERVER_PORT=9091
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=when-authorized
      - MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true
      # Production specific settings
      - LOGGING_LEVEL_ROOT=WARN
      - LOGGING_LEVEL_COM_INCORA=INFO
      # Performance tuning
      - JAVA_OPTS=-Xms2g -Xmx4g -XX:+UseG1GC
    volumes:
      # Volume mounts for production
      - ics-service-msds-prod:/msds
      - ics-service-receiptimages-prod:/receiptimages
      - ics-service-docimages-prod:/docimages
    healthcheck:
      test: ["CMD", "curl", "-f",
             "http://localhost:9091/actuator/health/liveness"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    depends_on:
      oracle-db-prod:
        condition: service_healthy
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 2G
          cpus: '1.0'
    networks:
      - ics-network-prod

  oracle-db-prod:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db-prod
    environment:
      - ORACLE_PWD=${ORACLE_ROOT_PASSWORD}
      - ORACLE_CHARACTERSET=AL32UTF8
    ports:
      - "1521:1521"
      - "5500:5500"  # Oracle Enterprise Manager
    volumes:
      - oracle-data-prod:/opt/oracle/oradata
      - oracle-backup-prod:/opt/oracle/backup
      # Initialize database with required user and schema
      - ../../init-scripts:/opt/oracle/scripts/startup
    healthcheck:
      test: ["CMD", "sqlplus", "-L",
             "sys/$$ORACLE_PWD@//localhost:1521/XE", "as", "sysdba",
             "<<<", "SELECT 1 FROM DUAL;"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 180s
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - ics-network-prod

volumes:
  # Named volumes for persistent data storage - Production
  ics-service-msds-prod:
    driver: local
  ics-service-receiptimages-prod:
    driver: local
  ics-service-docimages-prod:
    driver: local
  oracle-data-prod:
    driver: local
  oracle-backup-prod:
    driver: local

networks:
  ics-network-prod:
    driver: bridge
    name: ics-network-prod
