
CONNECT SYSTEM/&ORACLE_PWD@XE;

BEGIN
   EXECUTE IMMEDIATE 'CREATE USER tcm_ops IDENTIFIED BY "' || '&TCMIS_DB_SECRET' || '"';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE = -1920 THEN
         NULL; -- User already exists
      ELSE
         RAISE;
      END IF;
END;
/

GRANT CONNECT, RESOURCE TO tcm_ops;
GRANT CREATE SESSION TO tcm_ops;
GRANT CREATE TABLE TO tcm_ops;
GRANT CREATE VIEW TO tcm_ops;
GRANT CREATE SEQUENCE TO tcm_ops;
GRANT CREATE PROCEDURE TO tcm_ops;
GRANT UNLIMITED TABLESPACE TO tcm_ops;

GRANT SELECT_CATALOG_ROLE TO tcm_ops;
GRANT EXECUTE_CATALOG_ROLE TO tcm_ops;

COMMIT;

EXIT;
